import { NextRequest, NextResponse } from 'next/server';
import { generateFullLP, generateFullLPWithPostHog, LPGenerationPrompt } from '@/lib/lp-generator';
import { TemplateConfig } from '@/types/template';
import { generateLPImages, createImageGenerationConfigFromTemplate } from '@/lib/image-generator';
import { writeFile, readFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const prompt: LPGenerationPrompt = body;

    // バリデーション
    if (!prompt.serviceName || !prompt.serviceDescription || !prompt.targetAudience || !prompt.mainBenefit) {
      return NextResponse.json(
        { success: false, error: 'Required fields: serviceName, serviceDescription, targetAudience, mainBenefit' },
        { status: 400 }
      );
    }

    // LP生成（PostHog設定を含む）
    console.log(`🚀 Generating LP for: ${prompt.serviceName}`);
    const result = await generateFullLPWithPostHog(prompt);

    if (!result.success || !result.config) {
      return NextResponse.json({
        success: false,
        error: 'Failed to generate LP',
        errors: result.errors
      }, { status: 500 });
    }

    // プロジェクト用ディレクトリ作成（products/2-validation配下）
    const projectName = prompt.serviceName.toLowerCase().replace(/[^a-z0-9]/g, '-');
    const timestamp = new Date().toISOString().slice(0, 10).replace(/-/g, '-');
    const projectDirName = `2025-09-011-${projectName}`;
    const projectBasePath = path.join(process.cwd(), '../../products/2-validation', projectDirName);
    const lpPath = path.join(projectBasePath, 'lp');
    const configsPath = path.join(lpPath, 'configs');
    const configPath = path.join(configsPath, 'config.json');
    
    // ディレクトリ作成
    if (!existsSync(projectBasePath)) {
      await mkdir(projectBasePath, { recursive: true });
    }
    if (!existsSync(lpPath)) {
      await mkdir(lpPath, { recursive: true });
    }
    if (!existsSync(configsPath)) {
      await mkdir(configsPath, { recursive: true });
    }

    let existingConfig: TemplateConfig = {} as TemplateConfig;

    if (existsSync(configPath)) {
      try {
        const existingConfigData = await readFile(configPath, 'utf-8');
        existingConfig = JSON.parse(existingConfigData);
      } catch (error) {
        console.warn('Failed to read existing config, using defaults');
      }
    }

    // 生成されたコンテンツと既存の設定をマージ
    const mergedConfig: TemplateConfig = {
      ...existingConfig,
      ...result.config,
      meta: {
        ...existingConfig.meta,
        ...result.config.meta
      },
      content: {
        ...existingConfig.content,
        ...result.config.content
      },
      settings: {
        ...existingConfig.settings,
        // 開発者設定は保持
        development: {
          showCopywritingTips: true,
          copywritingTipsPosition: 'bottom',
          showSectionGuides: false,
          ...existingConfig.settings?.development
        }
      },
      theme: existingConfig.theme || {
        colors: {
          primary: '#3B82F6',
          secondary: '#8B5CF6',
          accent: '#EC4899',
          background: '#FFFFFF',
          text: '#1F2937',
          textLight: '#6B7280'
        },
        fonts: {
          heading: "'Inter', sans-serif",
          body: "'Inter', sans-serif"
        },
        gradients: {
          primary: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          secondary: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)'
        }
      },
      assets: existingConfig.assets || {
        logo: '/images/logo.svg',
        favicon: '/favicon.ico',
        images: {}
      }
    };

    // config.jsonに保存
    await writeFile(configPath, JSON.stringify(mergedConfig, null, 2));

    // 画像生成（有効な場合）
    let imageGenerationResult = null;
    if (mergedConfig.imageGeneration?.enabled) {
      console.log('🎨 Image generation is enabled, starting image generation...');
      const imageGenConfig = createImageGenerationConfigFromTemplate(mergedConfig);
      if (imageGenConfig) {
        const imagesOutputDir = path.join(lpPath, 'images');
        if (!existsSync(imagesOutputDir)) {
          await mkdir(imagesOutputDir, { recursive: true });
        }
        try {
          imageGenerationResult = await generateLPImages(imageGenConfig, imagesOutputDir);
          console.log(`✅ Image generation completed: ${imageGenerationResult.success}/${imageGenerationResult.total} images`);
        } catch (error) {
          console.error('Image generation failed:', error);
          imageGenerationResult = {
            success: 0,
            total: 0,
            errors: [error instanceof Error ? error.message : 'Unknown image generation error']
          };
        }
      }
    }

    // product.yamlファイルも作成
    const productYamlContent = `# Generated by LP Suite on ${new Date().toISOString()}
name: "${prompt.serviceName}"
description: "${prompt.serviceDescription}"
target_audience: "${prompt.targetAudience}"
main_benefit: "${prompt.mainBenefit}"
pricing: "${prompt.pricing || 'TBD'}"
brand_tone: "${prompt.brandTone || 'Professional'}"

# Project metadata
created_date: "${new Date().toISOString().slice(0, 10)}"
status: "validation"
lp_generated: true
posthog_enabled: ${result.posthogSetup?.success || false}

# Validation metrics targets
targets:
  lp_cvr: "3.0%"
  cpa: "3000円以下"
  test_duration: "7日間"
  traffic_target: "500UU"

# Competitor analysis
competitors:
  - name: "Peatix"
    strength: "会員ベースのターゲティング"
    weakness: "他媒体統合なし"
  - name: "Eventbrite" 
    strength: "広告統合"
    weakness: "日本ローカル浸透限定的"
  - name: "connpass"
    strength: "IT系強い"
    weakness: "非IT領域拡張性限定的"
`;
    
    const productYamlPath = path.join(projectBasePath, 'product.yaml');
    await writeFile(productYamlPath, productYamlContent);

    console.log(`✅ LP generated and saved for: ${prompt.serviceName}`);

    return NextResponse.json({
      success: true,
      config: mergedConfig,
      generatedSections: Object.keys(result.config.content || {}),
      posthogSetup: result.posthogSetup,
      imageGeneration: imageGenerationResult,
      errors: result.errors,
      projectPath: projectBasePath,
      message: `LP generated successfully for ${prompt.serviceName}${result.posthogSetup?.success ? ' (PostHog analytics configured)' : ''}${imageGenerationResult ? ` (${imageGenerationResult.success}/${imageGenerationResult.total} images generated)` : ''}`
    });

  } catch (error) {
    console.error('LP generation error:', error);
    return NextResponse.json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({
    message: 'LP Generator API',
    endpoints: {
      'POST /api/generate-lp': 'Generate a complete landing page with PostHog analytics',
    },
    required_fields: ['serviceName', 'serviceDescription', 'targetAudience', 'mainBenefit'],
    optional_fields: ['pricing', 'competitorAnalysis', 'brandTone', 'postHogConfig']
  });
}