repos:
  - repo: local
    hooks:
      - id: secretlint
        name: secretlint
        entry: npx secretlint
        language: system
        files: \.(js|ts|jsx|tsx|json|md|env)$
        exclude: node_modules/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict