/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.25.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import {
  ActionBuilder,
  MutationBuilder,
  QueryBuilder,
  DatabaseReader,
  DatabaseWriter,
} from "convex/server";
import { GenericId } from "convex/values";

/**
 * Define a query in this Convex app's public API.
 *
 * This function will be allowed to read your Convex database and will be accessible from the client.
 *
 * @param func - The query function. It receives a `DatabaseReader` as a first argument.
 * @returns The wrapped query. Include this as an `export` to add it to your app's API.
 */
export declare const query: QueryBuilder<DatabaseReader, "public">;

/**
 * Define a mutation in this Convex app's public API.
 *
 * This function will be allowed to modify your Convex database and will be accessible from the client.
 *
 * @param func - The mutation function. It receives a `DatabaseWriter` as a first argument.
 * @returns The wrapped mutation. Include this as an `export` to add it to your app's API.
 */
export declare const mutation: MutationBuilder<DatabaseWriter, "public">;

/**
 * Define an action in this Convex app's public API.
 *
 * An action can call third-party services and is not run within a database transaction.
 *
 * @param func - The action function.
 * @returns The wrapped action. Include this as an `export` to add it to your app's API.
 */
export declare const action: ActionBuilder;

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage for example:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: any;

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage for example:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: any;