# AI自分時間コーチ - 時間の質を高める新習慣

# 基本情報
productId: "2025-08-003-ai-coach"
name: "AI自分時間コーチ"
slug: "ai-coach"
category: "ライフスタイル"

# メタデータ  
description: "忙しい日常の中で自分時間の質を高める習慣作りをサポート"
longDescription: |
  20-30代の忙しいビジネスパーソン向け。
  AIコーチが一人ひとりのライフスタイルを分析し、
  自分時間の使い方を最適化。短時間でも充実感のある習慣作りを実現します。
  
# 現在状態
currentPhase: 1                        # 1=LP作成・検証中
status: "validation"                   # LP検証段階
createdAt: "2025-08-01"               # 企画開始日
lastUpdated: "2025-08-20"             # 最終更新日

# ビジネス情報
pricing:
  model: "subscription"                # サブスクリプション
  price: "月額 ¥2,980"
  currency: "JPY"
  
target:
  persona: "20-30代忙しいビジネスパーソン"
  segment: "BtoC"
  marketSize: "large"

# 技術情報
tech:
  repository: ""                       # 個別リポジトリは未作成
  deployUrl: ""                        # 本番URL（未設定）
  lpUrl: "https://unson-lp-ai-coach.vercel.app"
  stagingUrl: ""                       # ステージング環境（未設定）

# サービス実装情報
implementation:
  servicePath: "./service"             # 統合後のサービスコード位置
  framework: "nextjs"                  # Next.js
  packageManager: "npm"                # npm
  buildCommand: "npm run build"        # ビルドコマンド
  devCommand: "npm run dev"            # 開発サーバー
  deployTarget: "vercel"               # Vercel
  nodeVersion: "18"                    # Node.js 18
  vercelProject: "unson-lp-ai-coach"   # Vercelプロジェクト名
  vercelTeam: "unson-llc"              # Vercelチーム名

# KPI現在値（スナップショット）
metrics:
  currentCVR: null                     # LP検証中（未確定）
  totalUsers: 0                        # LP段階
  revenue: 0                           # 収益化前
  monthlyUsers: 0                      # LP段階
  lastMetricsUpdate: "2024-12-20"

# プレイブック実行履歴
playbookHistory:
  - phase: 1
    playbook: "PB-001"
    version: "1.0.0"  
    startDate: "2024-12-15"
    endDate: "2024-12-20"
    outcome: "in_progress"             # 現在実行中
    keyMetrics:
      cvr: null                        # 測定中
      sessions: 320                    # 中間値
    notes: "LP検証実行中。ライフスタイル改善のニーズ確認中"

# フェーズ移行履歴  
phaseHistory:
  - from: 0
    to: 1
    date: "2024-12-15"
    reason: "企画完了、LP検証開始"
    approver: "product-team"

# チーム・責任者
team:
  owner: "unson-team"
  contributors: ["growth-team", "lifestyle-designer"]
  reviewers: ["product-lead"]

# 関連情報
links:
  designDoc: ""
  marketResearch: ""
  competitorAnalysis: ""
  
# タグ・分類
tags: ["ライフスタイル", "時間管理", "習慣化", "セルフコーチング", "AIパーソナライズ"]
keywords: ["自分時間", "時間の質", "習慣化", "ライフスタイル", "AI"]

# 終了時情報（使用しない）
termination:
  date: null
  reason: ""
  finalMetrics: {}
  lessonsLearned: ""