# AIレガシー・クリエーター - 家族の知恵を未来に繋ぐ

# 基本情報
productId: "2025-08-004-ai-legacy-creator"
name: "AIレガシー・クリエーター"
slug: "ai-legacy-creator"
category: "ファミリー"

# メタデータ  
description: "大切な人の知恵や想いをAIが整理し、家族の絆を深める"
longDescription: |
  50-60代の方向け。AIが家族の会話や思い出を分析し、
  次世代に伝えたい知恵や価値観を美しい形で残すお手伝い。
  デジタル遺産として家族の絆を未来へ繋ぎます。
  
# 現在状態
currentPhase: 1                        # 1=LP作成・検証中
status: "validation"                   # LP検証段階
createdAt: "2025-08-01"               # 企画開始日
lastUpdated: "2025-08-20"             # 最終更新日

# ビジネス情報
pricing:
  model: "one-time"                    # 買い切り
  price: "¥19,800"
  currency: "JPY"
  
target:
  persona: "50-60代（家族想いの方）"
  segment: "BtoC"
  marketSize: "medium"

# 技術情報
tech:
  repository: ""                       # 個別リポジトリは未作成
  deployUrl: ""                        # 本番URL（未設定）
  lpUrl: "https://unson-lp-ai-legacy-creator.vercel.app"
  stagingUrl: ""                       # ステージング環境（未設定）

# サービス実装情報
implementation:
  servicePath: "./service"             # 統合後のサービスコード位置
  framework: "nextjs"                  # Next.js
  packageManager: "npm"                # npm
  buildCommand: "npm run build"        # ビルドコマンド
  devCommand: "npm run dev"            # 開発サーバー
  deployTarget: "vercel"               # Vercel
  nodeVersion: "18"                    # Node.js 18
  vercelProject: "unson-lp-ai-legacy-creator"  # Vercelプロジェクト名
  vercelTeam: "unson-llc"              # Vercelチーム名

# KPI現在値（スナップショット）
metrics:
  currentCVR: null                     # LP検証中（未確定）
  totalUsers: 0                        # LP段階
  revenue: 0                           # 収益化前
  monthlyUsers: 0                      # LP段階
  lastMetricsUpdate: "2024-12-20"

# プレイブック実行履歴
playbookHistory:
  - phase: 1
    playbook: "PB-001"
    version: "1.0.0"  
    startDate: "2024-12-15"
    endDate: "2024-12-20"
    outcome: "in_progress"             # 現在実行中
    keyMetrics:
      cvr: null                        # 測定中
      sessions: 180                    # 中間値
    notes: "LP検証実行中。家族の絆・遺産継承のニーズ確認中"

# フェーズ移行履歴  
phaseHistory:
  - from: 0
    to: 1
    date: "2024-12-15"
    reason: "企画完了、LP検証開始"
    approver: "product-team"

# チーム・責任者
team:
  owner: "unson-team"
  contributors: ["growth-team", "family-tech-specialist"]
  reviewers: ["product-lead"]

# 関連情報
links:
  designDoc: ""
  marketResearch: ""
  competitorAnalysis: ""
  
# タグ・分類
tags: ["ファミリー", "デジタル遺産", "知恵継承", "家族の絆", "AI分析"]
keywords: ["家族", "遺産", "知恵", "継承", "AI"]

# 終了時情報（使用しない）
termination:
  date: null
  reason: ""
  finalMetrics: {}
  lessonsLearned: ""